default: &default
  adapter: postgresql
  encoding: unicode
  # host: localhost
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: postgres
  # password:

development:
  <<: *default
  database: app_name_development

test:
  <<: *default
  database: app_name_test

staging:
  <<: *default
  database: app_name_staging

production:
  <<: *default
  database: app_name_production